- docs/anyedge/anyedge.md
- docs/customer/cli.md
- docs/customer/customer.md
- docs/customer/did.md
- docs/guides/monitoring.md
- docs/routing-strategy.md
https://bani--connexcs-docs.netlify.app/customer/cli/
This will BLOCK all USA Freephone numbers
^((?!^1(800|833|844|855|866|877|888)).)*$
https://bani--connexcs-docs.netlify.app/customer/cli/#how-to-invert-a-regular-expression
https://bani--connexcs-docs.netlify.app/customer/did/
**Done**
https://bani--connexcs-docs.netlify.app/customer/did/#billing
> CPS correction

- docs/acronyms-and-definitions.md
- docs/calling-card.md
- docs/changing-language.md
- docs/changing-password.md
- docs/dnc.md
- docs/feature-list.md
- docs/guides/3dig-ext.md
- docs/guides/doc-guide.md
- docs/limiting-cps.md
- docs/logging-out.md
- docs/number-manipulation.md
- docs/routing-strategy.md
https://bani-2022-12-28--connexcs-docs.netlify.app/acronyms-and-definitions/
https://bani-2022-12-28--connexcs-docs.netlify.app/changing-language/
https://bani-2022-12-28--connexcs-docs.netlify.app/changing-password/
https://bani-2022-12-28--connexcs-docs.netlify.app/logging-out/
https://bani-2022-12-28--connexcs-docs.netlify.app/number-manipulation/
https://bani-2022-12-28--connexcs-docs.netlify.app/guides/doc-guide/
https://bani-2022-12-28--connexcs-docs.netlify.app/guides/3dig-ext/
https://bani-2022-12-28--connexcs-docs.netlify.app/dnc/
https://bani-2022-12-28--connexcs-docs.netlify.app/calling-card/
https://bani-2022-12-28--connexcs-docs.netlify.app/limiting-cps/
https://bani-2022-12-28--connexcs-docs.netlify.app/feature-list/ …
> Bani-2022-12-28

- docs/billing-basics.md
- docs/billing.md
- docs/credit-control.md
- docs/guides/billing-guide.md
- docs/guides/stir-shaken-fcc.md
- docs/voucher.md
https://bani-2022-12-27--connexcs-docs.netlify.app/guides/stir-shaken-fcc/
https://bani-2022-12-27--connexcs-docs.netlify.app/guides/billing-guide/
https://bani-2022-12-27--connexcs-docs.netlify.app/billing-basics/
https://bani-2022-12-27--connexcs-docs.netlify.app/billing/
https://bani-2022-12-27--connexcs-docs.netlify.app/credit-control/
https://bani-2022-12-27--connexcs-docs.netlify.app/voucher/
> Bani 2022 12 27

- docs/customer-portal/cp-alert.md
- docs/customer-portal/cp-audio.md
- docs/customer-portal/cp-contracts.md
- docs/customer-portal/cp-documents.md
- docs/customer-portal/cp-group.md
- docs/customer-portal/cp-package.md
- docs/customer-portal/cp-payment.md
- docs/customer-portal/cp-queue.md
- docs/customer-portal/cp-recording.md
- docs/customer-portal/cp-routes.md
https://ban-customerportal-2022-12-30--connexcs-docs.netlify.app/customer-portal/cp-group/
https://ban-customerportal-2022-12-30--connexcs-docs.netlify.app/customer-portal/cp-queue/
https://ban-customerportal-2022-12-30--connexcs-docs.netlify.app/customer-portal/cp-audio/
https://ban-customerportal-2022-12-30--connexcs-docs.netlify.app/customer-portal/cp-alert/
https://ban-customerportal-2022-12-30--connexcs-docs.netlify.app/customer-portal/cp-contracts/
https://ban-customerportal-2022-12-30--connexcs-docs.netlify.app/customer-portal/cp-documents/
https://ban-customerportal-2022-12-30--connexcs-docs.netlify.app/customer-portal/cp-payment/
https://ban-customerportal-2022-12-30--connexcs-docs.netlify.app/customer-portal/cp-package/ …
> bani-ccustomerportal-2022-12-30

- docs/customer/cli.md
- docs/customer/did.md
- docs/setup/advanced/fraud.md
- docs/setup/settings/servers.md
Total Calls:** Total number of calls in a day.
https://bani-2023-01-02--connexcs-docs.netlify.app/setup/advanced/fraud/#detection-parameters-and-limits
https://bani-2023-01-02--connexcs-docs.netlify.app/setup/settings/servers/#server-config
**Whenever any of the above settings get modified, it's recommended to hit the Install Server.**
> Bani-2023-01-02

- docs/billing.md
- docs/credit-control.md
- docs/customer-portal/interconnect.md
- docs/far-end-nat-traversal.md
- docs/guides/tshoot-media.md
**CAPACITY REQUIREMENTS**
1. The number of channels required?
2. The number of CPS required?
3. What's the ACD?
4. What's the ASR?
5. What percentage of this traffic is already running on your infrastructure?
6. Do all these calls require Media Proxy, if so please specify volumes?
7. Do you need Transcoding or Call Recording, if so please specify volumes?
**TOPOGRAPHICAL REQUIREMENTS**
1. Please list all your customers IP Addresses along with locations if known:
2. If the aforementioned traffic isn't equally distributed between all IP addresses, please provide a break down.
3. Please list all carriers IP addresses where this traffic is most likely going to get transmitted to, along with locations if known.
4. If the aforementioned traffic isn't equally distributed between all IP …
> Bani-debuggingmedia

- docs/changing-language.md
- docs/files.md
**1. SSML for TTS**
In addition, we also support [SSML](https://cloud.google.com/text-to-speech/docs/ssml) for our TTS.
https://bani-tts--connexcs-docs.netlify.app/files/
> ssml for tts

- docs/api.md
You can find the API specification (new version) here: https://app.connexcs.com/api/api-spec/v3
https://bani-swagger--connexcs-docs.netlify.app/api/
> api swagger

- docs/webphone.md
https://bani-webphone--connexcs-docs.netlify.app/webphone/#dynamic-buttons
> Bani webphone

- docs/customer/cli.md
- docs/customer/invoices.md
- docs/customer/payment.md
- docs/setup/advanced/firewall.md
- docs/setup/advanced/rtp-block.md
- docs/setup/config/packages.md
- docs/setup/settings/options.md
1. Setup> Settings > Options
https://bani-2024-01-5--connexcs-docs.netlify.app/setup/settings/options/#__tabbed_1_3
2. Payment 
https://bani-2024-01-5--connexcs-docs.netlify.app/customer/payment/
Added (Description): Please note add a # symbol for starting a private comment to store private information along with the public information.
3. Firewall 
https://bani-2024-01-5--connexcs-docs.netlify.app/setup/advanced/firewall/
Added: You can only enter a single IP
4. CLI Modifiers
https://bani-2024-01-5--connexcs-docs.netlify.app/customer/cli/#use-pre-asserted-identity-as-cli
> Options, Payment, Firewall, CLI

- docs/class5/connexml.md
[ConneXML - ConnexCS Documentation (bani-connexml2--connexcs-docs.netlify.app)](https://bani-connexml2--connexcs-docs.netlify.app/class5/connexml/#dial)[ConneXML - ConnexCS Documentation (bani-connexml2--connexcs-docs.netlify.app)](https://bani-connexml2--connexcs-docs.netlify.app/class5/connexml/#dial)[ConneXML - ConnexCS Documentation (bani-connexml2--connexcs-docs.netlify.app)](https://bani-connexml2--connexcs-docs.netlify.app/class5/connexml/#dial)
> ConneXML> Dial > Voicemail and Voicemail inbox

- docs/class5/connexml.md
1. Dynamic Dial: https://bani-connexml12--connexcs-docs.netlify.app/class5/connexml/#dynamic-dial
2. Press DTMF Variable: https://bani-connexml12--connexcs-docs.netlify.app/class5/connexml/#press-dtmf-variable
3. Before: https://bani-connexml12--connexcs-docs.netlify.app/class5/connexml/#before
4. Stream: https://bani-connexml12--connexcs-docs.netlify.app/class5/connexml/#stream
5. Echo: https://bani-connexml12--connexcs-docs.netlify.app/class5/connexml/#echo
6. Set: https://bani-connexml12--connexcs-docs.netlify.app/class5/connexml/#set
7. statuscallbackevent, statuscallback, statuscallbackmethod: https://bani-connexml12--connexcs-docs.netlify.app/class5/connexml/#dial
> Bani connexml12

- docs/class5/connexml.md
- docs/guides/tshoot-media.md
https://bani-connexml281124--connexcs-docs.netlify.app/class5/connexml/#stream
|**Attribute**|**Description**|**Options**|**Default Method**|
|-------------|---------------|-----------|-------|
|`mix_type`| Determines the type of audio stream|1. `mono`: Single channel with only the caller's audio.<br> 2. `mixed`: Single channel combining both caller and callee audio.</br><br> 3.`stereo`: Two channels; one for the caller and one for the callee.</br>|`mono`|
|**Noun**|**Description**|  
|--------|---------------|
|`Parameter`|Its used to send key-value pairs to the WebSocket server.|
!!! Example "Example"
    ``` xml
    <?xml version="1.0" encoding="UTF-8"?>
    <Response>
        <Start>
            <Stream url="[ws://fr1js1.connexcs.net:3001"](ws://fr1js1.connexcs.net:3001&quot;) …
```
> Condition field, Variables (wrap around, blocks)

- docs/class5/connexml.md
https://bani-connexmluser--connexcs-docs.netlify.app/class5/connexml/#dial
|**Noun**|**Attribute**|**Description**|**Options**|**Default Method**|
|--------|--------|-----|-----------|------------------|
|`Voicemail`|`Voicemail Inbox`| It sends you to the inbox to leave a message|
||`user`|The user attribute specifies the SIP user|
18. **user**
        ``` xml
        <?xml version="1.0" encoding="UTF-8"?>
        <Response>
            <Dial>
                <Voicemail inbox="true" user="2890">
                </Voicemail>
            </Dial>
        </Response>
        ```
> User attribute in voicemail

- docs/class5/connexml.md
https://bani-jonsir--connexcs-docs.netlify.app/class5/connexml/
> Removed dev server

- docs/customer/auth.md
- docs/guides/osi-model.md
https://bani-senlal--connexcs-docs.netlify.app/customer/auth/#enable-sip-user-authentication
+ **Smart Extension**: It simplifies call transfers and enables advanced features like call barging and interception by centralizing REFER message handling within the Class 5 system. Unlike traditional SIP workflows, where the UAC or softphone manages transfers, this approach offloads complexity to us, enhancing functionality, user experience, and control through seamless integration of Class 4 and Class 5 systems.
          
          + **Smart Extension Workflow**:
            ```mermaid
            graph TD
            %% Define node styles
            classDef startEnd fill:#d1e7dd,stroke:#0f5132,stroke-width:2px,font-weight:bold;
            classDef process …
```
> Smart Extension (SIP User Auth); Application, Network and SIP Latency (OSI Model)

- docs/anyedge/anyedge.md
- docs/files.md
- docs/guides/tshoot-media.md
- docs/security.md
- docs/setup/settings/dns.md
We support the automatic archival of rate cards.
These can be downloaded in `.csv` format for convenient access and record-keeping.
!!! Info
    1. We support ZRTP and video pass-through functionalities, enabling seamless transmission from customers to carriers.
    2. Our platform provides comprehensive support for both IPv4 and IPv6 address protocols.
!!! Info "Key Capabilities of DNS"
    1. Free subdomains are included with our service offerings.
    2. Efficiently handles large-scale DNS queries with high availability and fast response times.
    3. Low latency DNS changes optimize configurations to reduce query resolution time.
At ConnexCS, our Auto Detect & Block Hack Attempts feature enhances security by automatically detecting and preventing unauthorized access.
It identifies …
> Feature list documentation 2

- docs/setup/integrations/api.md
- docs/setup/integrations/portal.md
1. API: [API - ConnexCS Documentation](https://bani-docrevamp26--connexcs-docs.netlify.app/setup/integrations/api/)
2. Portal: [Portal - ConnexCS Documentation](https://bani-docrevamp26--connexcs-docs.netlify.app/setup/integrations/portal/#__tabbed_2_4)
> Setup > Integration > API, Portal

- docs/apps/components/button.md
- docs/apps/components/dialog.md
Button: :https://bani-saurabhbutton--connexcs-docs.netlify.app/apps/components/button/g
Dialog: https://bani-saurabhbutton--connexcs-docs.netlify.app/apps/components/dialog/
> Button and Dialog -enable and disable buttons

- docs/setup/integrations/portal.md
https://bani-docrevamp26--connexcs-docs.netlify.app/setup/integrations/portal/#__tabbed_1_2
> Setup > Integration > Portal > User Access Area

- docs/class5/connexml.md
1. callerId in Dial
https://bani-connexml-corrections--connexcs-docs.netlify.app/class5/connexml/#dial
2. Transfer in Press
https://bani-connexml-corrections--connexcs-docs.netlify.app/class5/connexml/#press
> ConneXML corrections

- docs/customer/alerts.md
- docs/customer/auth.md
https://bani-docrevamp5--connexcs-docs.netlify.app/customer/auth/
> Auth in Customers

- docs/customer/alerts.md
- docs/customer/alias.md
https://bani-docrevamp6--connexcs-docs.netlify.app/customer/alias/
> Alias in Customers

- docs/customer/cli.md
https://bani-docrevamp7--connexcs-docs.netlify.app/customer/cli/
> CLI routing in Customer

- docs/customer/dialogs.md
- docs/customer/latest-calls.md
- docs/customer/payment.md
- docs/customer/route-stats.md
- docs/customer/stats.md
Payments: [Payment - ConnexCS Documentation](https://bani-docrevamp9--connexcs-docs.netlify.app/customer/payment/)
Stats: [Stats - ConnexCS Documentation](https://bani-docrevamp9--connexcs-docs.netlify.app/customer/stats/)
Route Stats: [Route Stats - ConnexCS Documentation](https://bani-docrevamp9--connexcs-docs.netlify.app/customer/route-stats/)
Latest calls: [Latest Calls - ConnexCS Documentation](https://bani-docrevamp9--connexcs-docs.netlify.app/customer/latest-calls/)
Dialogs: [Dialogs - ConnexCS Documentation](https://bani-docrevamp9--connexcs-docs.netlify.app/customer/dialogs/)
> Payments, Stats, Route-stats, Latest-calls, Dialogs

- docs/api.md
- docs/apps/architecture/script.md
- docs/calling-card.md
- docs/carrier/carrier-cdr.md
- docs/class5/creating-conference.md
- docs/customer/auth.md
- docs/customer/cli.md
- docs/customer/customer.md
- docs/customer/main.md
- docs/customer/routing.md
- docs/feature-list.md
- docs/guides/monitoring.md
- docs/guides/spam-callsblock.md
- docs/guides/tshoot-media.md
- docs/logging.md
- docs/provider-ratecard.md
- docs/setup/information/stir-shaken.md
- docs/setup/integrations/api.md
- docs/setup/integrations/portal.md
- docs/setup/settings/data-retention.md
- docs/tag.md
- mkdocs.yml
https://bani-ravisc--connexcs-docs.netlify.app/apps/architecture/script/#export
> Export and Import modules in Scriptforge

- docs/class5/connexml.md
1. hanguponstarcontext
https://bani-context--connexcs-docs.netlify.app/class5/connexml/#dial
2. Enter verb and context noun
https://bani-context--connexcs-docs.netlify.app/class5/connexml/#enter
> ConneXML- enter, context, hjanguponstarcontext

- docs/apps/architecture/button-builder.md
- docs/apps/architecture/script.md
1. Scriptforge: [Script Forge - ConnexCS Documentation](https://bani-docrevamp19--connexcs-docs.netlify.app/apps/architecture/script/)
2. Button Builder: [Button Builder - ConnexCS Documentation](https://bani-docrevamp19--connexcs-docs.netlify.app/apps/architecture/button-builder/)
> Scriptforge, Button Builder in Apps Platform
